# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17c727bdf6e7cd8b39ce124fc0b86fa0ae674f9803cd80fc218616990ccfd74125c135544d64394d988985c734e9437f8369ae230a48b28824d7d47d05d9917f

test:
  secret_key_base: 13dee65c6e5af3f41ec410361dc5b04b0b791fe4b3cc7b0cfc13ad17397e4d4ec6bbc990a969364990c232000a2cd8c791a26b48554fb5a8777d85df7b2e6111

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
